fmesher code update
davidbolin/excursions pull request #2
Opened 2023-10-18 12:19 UTC by enoch26

Updated the codes with fmesher functions.

2023-10-18 12:53 UTC, finnlindgren requested changes

2023-10-18 12:53 UTC, finnlindgren commented on R/contourmap.inla.R
The contourmap.inla example is specifically about using inla(), so would be safer to keep using the `inla.*` functions here, as they have a specific parameterisation.  Otherwise, should change to inla.spde2.pcmatern() as well, but even then there is no strict guarantee that that matches fm_matern_precision().

2023-10-18 12:53 UTC, finnlindgren commented on man/continuous.Rd
> -  spde <- inla.spde2.matern(mesh, alpha = 2)
Good removal.

2023-10-18 12:53 UTC, finnlindgren commented on R/geometry.R
Here the change to `fm_*` seems sensible, but would be nicer to use other `rho` and `sigma` values; the `sqrt(8)` and `sqrt(2*pi)` are only there to match the less interpretable kappa and tau from the `contourmap.inla` example. Could use directly chosen values here instead, as it doesn't involve INLA at all.

2023-10-18 12:53 UTC, finnlindgren commented on R/geometry.R
...and since it doesn't involve INLA, can also remove the require.nowarnings() call from the beginning of the example.

2023-10-18 13:00 UTC, enoch26 commented on R/contourmap.inla.R
That sounds reasonable to me.

2023-10-18 13:29 UTC, enoch26 commented on R/geometry.R
Fixed the require.nowarnings()

2023-10-18 13:31 UTC, enoch26 commented on R/geometry.R
We can discuss the sensible values for rho and sigma tomorrow.

2023-10-18 13:42 UTC, finnlindgren commented on R/geometry.R
> +#' if (require("INLA") && require("fmesher")) {
require.nowarnings() is meant to be used whenever requiring INLA. If INLA isn't required, remove the require() call entirely.

2023-10-18 13:43 UTC, finnlindgren commented
I think you forgot to run `devtools:document()`? (Also run `devtools::check()` on your system)

2023-10-19 10:07 UTC, finnlindgren approved these changes

2023-10-19 10:44 UTC, merged